/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'frank' at '4/23/17 9:00 AM' with Gradle 3.0
 *
 * @author frank, @date 4/23/17 9:00 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
